// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ihUQEbdSxsJvuf4t0YP7Sy9XYp-HRKs',
    appId: '1:562353221228:web:0b16b21f79aac8ac8fb249',
    messagingSenderId: '562353221228',
    projectId: 'lector-global-1c462',
    authDomain: 'lector-global-1c462.firebaseapp.com',
    storageBucket: 'lector-global-1c462.firebasestorage.app',
    measurementId: 'G-CC7D3GYRYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfvs1UKEmLVX1nkmiNNnBIUuSJZ0AvBb0',
    appId: '1:562353221228:android:a8f8756a3d1ebfc38fb249',
    messagingSenderId: '562353221228',
    projectId: 'lector-global-1c462',
    storageBucket: 'lector-global-1c462.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ihUQEbdSxsJvuf4t0YP7Sy9XYp-HRKs',
    appId: '1:562353221228:web:9cd540c805fd3f998fb249',
    messagingSenderId: '562353221228',
    projectId: 'lector-global-1c462',
    authDomain: 'lector-global-1c462.firebaseapp.com',
    storageBucket: 'lector-global-1c462.firebasestorage.app',
    measurementId: 'G-1G5XKMDWS6',
  );
}
