name: lector_global
description: "Aplicación para mejorar la comprensión lectora en todos los idiomas."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

  provider: ^6.0.0

  cupertino_icons: ^1.0.8

  audioplayers: ^6.4.0

  firebase_core: ^2.30.0

  firebase_auth: ^4.17.5

  google_sign_in: ^6.3.0

  flutter_facebook_auth: ^6.1.1

  plugin_platform_interface: ^2.1.8

  flutter_svg: ^2.0.7
  firebase_analytics: ^10.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/lang/
    - assets/images/
