name: lector_global
description: "A new Flutter project."
# Evita que este paquete sea publicado accidentalmente en pub.dev.
publish_to: "none" # Elimina esta línea si deseas publicar en pub.dev

# Versión y número de compilación de tu aplicación.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Iconos de estilo Cupertino para iOS.
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Reglas de lint recomendadas para Flutter.
  flutter_lints: ^5.0.0

flutter:
  # Habilita el uso de los iconos de Material.
  uses-material-design: true

  # Carga todos los archivos dentro de la carpeta assets/, incluyendo sounds/.
  assets:
    - assets/
