<<<<<<< HEAD
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
=======
// -----------------------------------------------------------------------------
// Archivo: lib/firebase_options.dart
// Descripción: Configuración automática generada por FlutterFire CLI para Firebase
// Última actualización: 04/05/2025 - Hora: 11:00 p.m. (Hora de Colombia)
// -----------------------------------------------------------------------------

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

>>>>>>> d67b3c5 (Versión estable de pantalla de inicio de sesión - Diseño limpio y funcional - 050520251722)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
<<<<<<< HEAD
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
=======
>>>>>>> d67b3c5 (Versión estable de pantalla de inicio de sesión - Diseño limpio y funcional - 050520251722)
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyD2ihUQEbdSxsJvuf4t0YP7Sy9XYp-HRKs',
    appId: '1:562353221228:web:0b16b21f79aac8ac8fb249',
    messagingSenderId: '562353221228',
    projectId: 'lector-global-1c462',
    authDomain: 'lector-global-1c462.firebaseapp.com',
    storageBucket: 'lector-global-1c462.firebasestorage.app',
    measurementId: 'G-CC7D3GYRYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfvs1UKEmLVX1nkmiNNnBIUuSJZ0AvBb0',
    appId: '1:562353221228:android:2da1afd6cf20e6298fb249',
    messagingSenderId: '562353221228',
    projectId: 'lector-global-1c462',
    storageBucket: 'lector-global-1c462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHyDeeGr59c9Z8KQqlZP_T7jGExaYNsZ0',
    appId: '1:562353221228:ios:b91996d075d7f5c78fb249',
    messagingSenderId: '562353221228',
    projectId: 'lector-global-1c462',
    storageBucket: 'lector-global-1c462.firebasestorage.app',
    androidClientId: '562353221228-affetitg1b1l6ijrvcan3pt9ncvki8hh.apps.googleusercontent.com',
    iosClientId: '562353221228-phs5ku5i6513t7ki7hm3p0enplngjpf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.lectorGlobal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHyDeeGr59c9Z8KQqlZP_T7jGExaYNsZ0',
    appId: '1:562353221228:ios:b91996d075d7f5c78fb249',
    messagingSenderId: '562353221228',
    projectId: 'lector-global-1c462',
    storageBucket: 'lector-global-1c462.firebasestorage.app',
    androidClientId: '562353221228-affetitg1b1l6ijrvcan3pt9ncvki8hh.apps.googleusercontent.com',
    iosClientId: '562353221228-phs5ku5i6513t7ki7hm3p0enplngjpf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.lectorGlobal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ihUQEbdSxsJvuf4t0YP7Sy9XYp-HRKs',
    appId: '1:562353221228:web:9cd540c805fd3f998fb249',
    messagingSenderId: '562353221228',
    projectId: 'lector-global-1c462',
    authDomain: 'lector-global-1c462.firebaseapp.com',
    storageBucket: 'lector-global-1c462.firebasestorage.app',
    measurementId: 'G-1G5XKMDWS6',
=======
    apiKey: "AIzaSyD2ihUQEbdSxsJvuf4t0YP7Sy9XYp-HRKs",
    authDomain: "lector-global-1c462.firebaseapp.com",
    projectId: "lector-global-1c462",
    storageBucket: "lector-global-1c462.appspot.com",
    messagingSenderId: "562353221228",
    appId: "1:562353221228:web:580e0b1018505a8e8fb249",
    measurementId: "G-4Z6182TTRE",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyD2ihUQEbdSxsJvuf4t0YP7Sy9XYp-HRKs",
    authDomain: "lector-global-1c462.firebaseapp.com",
    projectId: "lector-global-1c462",
    storageBucket: "lector-global-1c462.appspot.com",
    messagingSenderId: "562353221228",
    appId: "1:562353221228:android:580e0b1018505a8e8fb249",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyD2ihUQEbdSxsJvuf4t0YP7Sy9XYp-HRKs",
    authDomain: "lector-global-1c462.firebaseapp.com",
    projectId: "lector-global-1c462",
    storageBucket: "lector-global-1c462.appspot.com",
    messagingSenderId: "562353221228",
    appId: "1:562353221228:ios:580e0b1018505a8e8fb249",
    iosBundleId: "com.example.lectorGlobal",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyD2ihUQEbdSxsJvuf4t0YP7Sy9XYp-HRKs",
    authDomain: "lector-global-1c462.firebaseapp.com",
    projectId: "lector-global-1c462",
    storageBucket: "lector-global-1c462.appspot.com",
    messagingSenderId: "562353221228",
    appId: "1:562353221228:ios:580e0b1018505a8e8fb249",
    iosBundleId: "com.example.lectorGlobal",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyD2ihUQEbdSxsJvuf4t0YP7Sy9XYp-HRKs",
    authDomain: "lector-global-1c462.firebaseapp.com",
    projectId: "lector-global-1c462",
    storageBucket: "lector-global-1c462.appspot.com",
    messagingSenderId: "562353221228",
    appId: "1:562353221228:windows:580e0b1018505a8e8fb249",
>>>>>>> d67b3c5 (Versión estable de pantalla de inicio de sesión - Diseño limpio y funcional - 050520251722)
  );
}
